### ISSUE TITLE
Moloch not saving pcap, only sessions

### ISSUE THREAD

**Issue by giraldo925** [sealingtech/EDCOP-MOLOCH#4]
Moloch was turned on Friday and left running over the weekend. It however does not appear to be saving pcap files. I say this because hardly any storage space was utilized on the disk drives. But also because I am unable to download pcap files for individual sessions. I can query sessions, but I can not actually get the raw pcap. Please see screenshots below , also linked articles to someone having similar issues. 

When I try to download pcap:
<img width="1235" alt="screen shot 2018-08-06 at 10 55 14 am" src="https://user-images.githubusercontent.com/39535038/43724139-48dce4ec-9967-11e8-81ee-fee1aa7dd11f.png">

Storage used should be greater: 
<img width="1211" alt="screen shot 2018-08-06 at 10 55 00 am" src="https://user-images.githubusercontent.com/39535038/43724145-4b1f6216-9967-11e8-82f0-68f2adf06e59.png">

https://groups.google.com/forum/#!topic/moloch-fpc/EKl2qj9b2IQ
https://groups.google.com/forum/#!topic/moloch-fpc/DfU5pkZjhZs

**Comment by miked235** [comment]
Fixed in merge #5
